# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\tscheduler\"\x07\n\x05\x45mpty\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\"f\n\x0eReserveRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\x12\x12\n\nservice_id\x18\x03 \x01(\t\x12\x11\n\tslot_time\x18\x04 \x01(\t\"k\n\x0fReserveResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07slot_id\x18\x02 \x01(\t\x12\x11\n\tleader_id\x18\x03 \x01(\x05\x12\x13\n\x0bleader_addr\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"I\n\nLeaderInfo\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x13\n\x0bleader_addr\x18\x02 \x01(\t\x12\x13\n\x0bi_am_leader\x18\x03 \x01(\x08\"6\n\x0cHeartbeatMsg\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x13\n\x0bleader_addr\x18\x02 \x01(\t\"\x8b\x01\n\x0f\x45lectionMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0cinitiator_id\x18\x02 \x01(\x05\x12\r\n\x05phase\x18\x03 \x01(\x05\x12\x0c\n\x04hops\x18\x04 \x01(\x05\x12\x11\n\tdirection\x18\x05 \x01(\t\x12\x11\n\tleader_id\x18\x06 \x01(\x05\x12\x11\n\torigin_id\x18\x07 \x01(\x05\x32\xf7\x01\n\tScheduler\x12\x44\n\x0bReserveSlot\x12\x19.scheduler.ReserveRequest\x1a\x1a.scheduler.ReserveResponse\x12\x36\n\x0bWhoIsLeader\x12\x10.scheduler.Empty\x1a\x15.scheduler.LeaderInfo\x12\x34\n\tHeartbeat\x12\x17.scheduler.HeartbeatMsg\x1a\x0e.scheduler.Ack\x12\x36\n\x08\x45lection\x12\x1a.scheduler.ElectionMessage\x1a\x0e.scheduler.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_ACK']._serialized_start=39
  _globals['_ACK']._serialized_end=56
  _globals['_RESERVEREQUEST']._serialized_start=58
  _globals['_RESERVEREQUEST']._serialized_end=160
  _globals['_RESERVERESPONSE']._serialized_start=162
  _globals['_RESERVERESPONSE']._serialized_end=269
  _globals['_LEADERINFO']._serialized_start=271
  _globals['_LEADERINFO']._serialized_end=344
  _globals['_HEARTBEATMSG']._serialized_start=346
  _globals['_HEARTBEATMSG']._serialized_end=400
  _globals['_ELECTIONMESSAGE']._serialized_start=403
  _globals['_ELECTIONMESSAGE']._serialized_end=542
  _globals['_SCHEDULER']._serialized_start=545
  _globals['_SCHEDULER']._serialized_end=792
# @@protoc_insertion_point(module_scope)
