# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerStub:
    """Scheduler service: dijalankan di setiap node cluster.
    Menangani RPC alokasi slot (dari Booking Service) DAN pesan election
    antar node (Hirschberg-Sinclair).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveSlot = channel.unary_unary(
                '/scheduler.Scheduler/ReserveSlot',
                request_serializer=scheduler__pb2.ReserveRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ReserveResponse.FromString,
                _registered_method=True)
        self.WhoIsLeader = channel.unary_unary(
                '/scheduler.Scheduler/WhoIsLeader',
                request_serializer=scheduler__pb2.Empty.SerializeToString,
                response_deserializer=scheduler__pb2.LeaderInfo.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/scheduler.Scheduler/Heartbeat',
                request_serializer=scheduler__pb2.HeartbeatMsg.SerializeToString,
                response_deserializer=scheduler__pb2.Ack.FromString,
                _registered_method=True)
        self.Election = channel.unary_unary(
                '/scheduler.Scheduler/Election',
                request_serializer=scheduler__pb2.ElectionMessage.SerializeToString,
                response_deserializer=scheduler__pb2.Ack.FromString,
                _registered_method=True)


class SchedulerServicer:
    """Scheduler service: dijalankan di setiap node cluster.
    Menangani RPC alokasi slot (dari Booking Service) DAN pesan election
    antar node (Hirschberg-Sinclair).
    """

    def ReserveSlot(self, request, context):
        """RPC bisnis: reservasi slot. Hanya LEADER yang boleh commit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhoIsLeader(self, request, context):
        """Tanya node siapa leader saat ini.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat dari leader ke follower (deteksi kegagalan).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Pesan election Hirschberg-Sinclair antar node (PROBE/REPLY/LEADER).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveSlot,
                    request_deserializer=scheduler__pb2.ReserveRequest.FromString,
                    response_serializer=scheduler__pb2.ReserveResponse.SerializeToString,
            ),
            'WhoIsLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.WhoIsLeader,
                    request_deserializer=scheduler__pb2.Empty.FromString,
                    response_serializer=scheduler__pb2.LeaderInfo.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=scheduler__pb2.HeartbeatMsg.FromString,
                    response_serializer=scheduler__pb2.Ack.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=scheduler__pb2.ElectionMessage.FromString,
                    response_serializer=scheduler__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.Scheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Scheduler:
    """Scheduler service: dijalankan di setiap node cluster.
    Menangani RPC alokasi slot (dari Booking Service) DAN pesan election
    antar node (Hirschberg-Sinclair).
    """

    @staticmethod
    def ReserveSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/ReserveSlot',
            scheduler__pb2.ReserveRequest.SerializeToString,
            scheduler__pb2.ReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WhoIsLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/WhoIsLeader',
            scheduler__pb2.Empty.SerializeToString,
            scheduler__pb2.LeaderInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/Heartbeat',
            scheduler__pb2.HeartbeatMsg.SerializeToString,
            scheduler__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/Election',
            scheduler__pb2.ElectionMessage.SerializeToString,
            scheduler__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
